version: "3.9"

services:
  server:
    build: .
    container_name: erovians-server
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:  # ✅ Ye add karo
      - .:/app
      - /app/node_modules  # ✅ node_modules ko override mat karo
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: erovians-redis
    ports:
      - "6379:6379"
    restart: unless-stopped